src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_courte;

    /**
     * @ORM\Column(type="text")
     */
    private $description_longue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix_journalier;

    /**
     * @ORM\Column(type="date")
     */
    private $date_enregitrement;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="chambre")
     */
    private $commandes;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="chambre")
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity=Dislike::class, mappedBy="chambre")
     */
    private $dislikes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->dislikes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): self
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): self
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregitrement(): ?\DateTimeInterface
    {
        return $this->date_enregitrement;
    }

    public function setDateEnregitrement(\DateTimeInterface $date_enregitrement): self
    {
        $this->date_enregitrement = $date_enregitrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setChambre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getChambre() === $this) {
                $commande->setChambre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setChambre($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getChambre() === $this) {
                $like->setChambre(null);
            }
        }

        return $this;
    }

    public function isLikeByUser(User $user)
    {
        foreach ($this->likes as $like) {
            if ($like->getUser() == $user) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return Collection<int, Dislike>
     */
    public function getDislikes(): Collection
    {
        return $this->dislikes;
    }

    public function addDislike(Dislike $dislike): self
    {
        if (!$this->dislikes->contains($dislike)) {
            $this->dislikes[] = $dislike;
            $dislike->setChambre($this);
        }

        return $this;
    }

    public function removeDislike(Dislike $dislike): self
    {
        if ($this->dislikes->removeElement($dislike)) {
            // set the owning side to null (unless already changed)
            if ($dislike->getChambre() === $this) {
                $dislike->setChambre(null);
            }
        }

        return $this;
    }

    public function isDislikeByUser(User $user)
    {
        foreach ($this->dislikes as $dislike) {
            if ($dislike->getUser() === $user) {
                return true;
            }
        }

        return false;
    }
}

src/Controller/Front/FrontAvisController.php
<?php

namespace App\Controller\Front;

use App\Entity\Avis;
use App\Form\AvisType;
use App\Repository\AvisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontAvisController extends AbstractController
{
    /**
     * @Route("avis", name="list_avis")
     */
    public function listAvis(
        AvisRepository $avisRepository,
        Request $request,
        EntityManagerInterface $entityManagerInterface
    ) {
        $avis = $avisRepository->findAll();

        $avi = new Avis();

        $aviForm = $this->createForm(AvisType::class, $avi);

        $aviForm->handleRequest($request);

        if ($aviForm->isSubmitted() && $aviForm->isValid()) {
            $entityManagerInterface->persist($avi);
            $entityManagerInterface->flush();

            return $this->redirectToRoute("list_avis");
        }

        return $this->render("front/avis_list.html.twig", [
            'avis' => $avis,
            'aviForm' => $aviForm->createView()
        ]);
    }

    /**
     * @Route("avis/search", name="avis_search")
     */
    public function avisSearch(AvisRepository $avisRepository, Request $request)
    {
        $term = $request->query->get('search');

        $avis = $avisRepository->searchByTerm($term);

        return $this->render("front/search_avis.html.twig", ['avis' => $avis, 'term' => $term]);
    }
}

src/Controller/Front/FrontChambreController.php
<?php

namespace App\Controller\Front;

use App\Entity\Commande;
use App\Entity\Dislike;
use App\Entity\Like;
use App\Form\FrontCommandeType;
use App\Repository\ChambreRepository;
use App\Repository\DislikeRepository;
use App\Repository\LikeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontChambreController extends AbstractController
{
    /**
     * @Route("chambres", name="front_chambre_list")
     */
    public function listChambre(ChambreRepository $chambreRepository)
    {
        $chambres = $chambreRepository->findAll();

        return $this->render("front/chambre_list.html.twig", ['chambres' => $chambres]);
    }

    /**
     * @Route("chambre/{id}", name="front_chambre_show")
     */
    public function showChambre($id, ChambreRepository $chambreRepository, Request $request, EntityManagerInterface $entityManagerInterface)
    {
        $chambre = $chambreRepository->find($id);

        $commande = new Commande();

        $commandeForm = $this->createForm(FrontCommandeType::class, $commande);

        $commandeForm->handleRequest($request);

        if ($commandeForm->isSubmitted() && $commandeForm->isValid()) {
            $date_arrivee = $commandeForm->get('date_arrivee')->getData();
            $date_depart = $commandeForm->get('date_depart')->getData();

            $interval = $date_arrivee->diff($date_depart);

            $prix_journalier = $chambre->getPrixJournalier();
            $prix_total = $interval->days * $prix_journalier;
            $commande->setPrixTotal($prix_total);
            $commande->setDateEnregistrement(new \DateTime("NOW"));
            $commande->setChambre($chambre);

            $entityManagerInterface->persist($commande);
            $entityManagerInterface->flush();

            return $this->redirectToRoute("front_chambre_list");
        }

        return $this->render("front/chambre_show.html.twig", [
            'chambre' => $chambre,
            'commandeForm' => $commandeForm->createView()
        ]);
    }

    /**
     * @Route("like/chambre/{id}", name="chambre_like")
     */
    public function likeChambre(
        $id,
        ChambreRepository $chambreRepository,
        EntityManagerInterface $entityManagerInterface,
        LikeRepository $likeRepository,
        DislikeRepository $dislikeRepository
    ) {
        $chambre = $chambreRepository->find($id);
        $user = $this->getUser();

        if (!$user) {
            return $this->json([
                'code' => 403,
                'message' => "Vous devez être connecté"
            ], 403);
        }

        if ($chambre->isLikeByUser($user)) {
            $like = $likeRepository->findOneBy(
                [
                    'chambre' => $chambre,
                    'user' => $user
                ]
            );

            $entityManagerInterface->remove($like);
            $entityManagerInterface->flush();

            return $this->json([
                'code' => 200,
                'message' => "Le like a bien été supprimé.",
                'likes' => $likeRepository->count(['chambre' => $chambre])
            ], 200);
        }

        if ($chambre->isDislikeByUser($user)) {
            $dislike = $dislikeRepository->findOneBy([
                'chambre' => $chambre,
                'user' => $user
            ]);

            $entityManagerInterface->remove($dislike);

            $like = new Like();

            $like->setChambre($chambre);
            $like->setUser($user);

            $entityManagerInterface->persist($like);
            $entityManagerInterface->flush();

            return $this->json([
                'code' => 200,
                'message' => "Le dislkie a été supprimé et le like a été ajouté",
                'likes' => $likeRepository->count(['chambre' => $chambre]),
                'dislikes' => $dislikeRepository->count(['chambre' => $chambre])
            ], 200);
        }

        $like = new Like();

        $like->setChambre($chambre);
        $like->setUser($user);

        $entityManagerInterface->persist($like);
        $entityManagerInterface->flush();

        return $this->json([
            'code' => 200,
            'message' => "Nouveau like bien enregistré",
            'likes' => $likeRepository->count(['chambre' => $chambre])
        ], 200);
    }

    /**
     * @Route("/dislike/chambre/{id}", name="dislike_chambre")
     */
    public function dislikeChambre(
        $id,
        ChambreRepository $chambreRepository,
        EntityManagerInterface $entityManagerInterface,
        DislikeRepository $dislikeRepository,
        LikeRepository $likeRepository
    ) {

        $chambre = $chambreRepository->find($id);
        $user = $this->getUser();

        if (!$user) {
            return $this->json([
                'code' => 403,
                "message" => "Vous être connecté"
            ], 403);
        }

        if ($chambre->isDislikeByUser($user)) {
            $dislike = $dislikeRepository->findOneBy([
                'chambre' => $chambre,
                'user' => $user
            ]);

            $entityManagerInterface->remove($dislike);

            $entityManagerInterface->flush();

            return $this->json([
                'code' => 200,
                'message' => "Le dislike a bien été supprimé",
                'dislikes' => $dislikeRepository->count(['chambre' => $chambre])
            ], 200);
        }

        if ($chambre->isLikeByUser($user)) {
            $like = $likeRepository->findOneBy([
                'chambre' => $chambre,
                'user' => $user
            ]);

            $entityManagerInterface->remove($like);

            $dislike = new Dislike();

            $dislike->setChambre($chambre);
            $dislike->setUser($user);

            $entityManagerInterface->persist($dislike);
            $entityManagerInterface->flush();

            return $this->json([
                'code' => 200,
                'message' => "Le like a été supprimé et le dislike a été ajouté",
                'likes' => $likeRepository->count(['chambre' => $chambre]),
                'dislikes' => $dislikeRepository->count(['chambre' => $chambre])
            ], 200);
        }

        $dislike = new Dislike();

        $dislike->setChambre($chambre);
        $dislike->setUser($user);

        $entityManagerInterface->persist($dislike);
        $entityManagerInterface->flush();

        return $this->json([
            'code' => 200,
            'message' => "Le dislike a bien été ajouté",
            'dislikes' => $dislikeRepository->count(['chambre' => $chambre])
        ], 200);
    }
}

src/Controller/Front/FrontHomeController.php
<?php

namespace App\Controller\Front;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\ChambreRepository;
use App\Repository\SliderRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class FrontHomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function Home(SliderRepository $sliderRepository)
    {
        $sliders = $sliderRepository->findAll();

        return $this->render('front/home.html.twig', ['sliders' => $sliders]);
    }

    /**
     * @Route("/search/", name="search")
     */
    public function search(ChambreRepository $chambreRepository, Request $request)
    {
        $term = $request->query->get("search");

        $chambres = $chambreRepository->searchByTerm($term);

        return $this->render("front/search.html.twig", ['chambres' => $chambres, 'term' => $term]);
    }

    /**
     * @Route("/inscription", name="inscription")
     */
    public function inscriotion(
        Request $request,
        EntityManagerInterface $entityManagerInterface,
        UserPasswordHasherInterface $userPasswordHasherInterface
    ) {
        $user = new User();

        $userForm = $this->createForm(UserType::class, $user);

        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {
            $user->setRoles(["ROLE_ADMIN"]);
            $user->setDateEnregistrement(new \DateTime("NOW"));

            $plainPassword = $userForm->get('password')->getData();

            $hashedPassword = $userPasswordHasherInterface->hashPassword($user, $plainPassword);

            $user->setPassword($hashedPassword);

            $entityManagerInterface->persist($user);
            $entityManagerInterface->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('front/user_form.html.twig', ['userForm' => $userForm->createView()]);
    }

    /**
     * @Route("contact", name="contact")
     */
    public function contact()
    {
        return $this->render("front/contact.html.twig");
    }

    /**
     * @Route("email/", name="email")
     */
    public function email(Request $request, MailerInterface $mailerInterface)
    {
        $email = $request->request->get('email');
        $nom = $request->request->get('nom');
        $prenom = $request->request->get('prenom');
        $sujet = $request->request->get('sujet');
        $categorie = $request->request->get('categorie');
        $message = $request->request->get('message');

        $mail = (new TemplatedEmail())
            ->from($email)
            ->to('hh@gmail.com')
            ->subject($sujet)
            ->htmlTemplate('front/email.html.twig')
            ->context([
                'message' => $message,
                'nom' => $nom,
                'prenom' => $prenom,
                'categorie' => $categorie,
                'sujet' => $sujet
            ]);

        $mailerInterface->send($mail);

        return $this->redirectToRoute('contact');
    }
}

templates/front/avis_list.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<form action="{{ path('avis_search') }}" method="get">
		<label for="search">Filtrer les avis</label>
		<select name="search" id="search">
			<option value="Hôtel">Hôtel</option>
			<option value="Chambre">Chambre</option>
			<option value="Restaurant">Restaurant</option>
		</select>
		<input type="submit" value="Filtrer" class="btn btn-primary">
	</form>

	<h1>Liste des avis</h1>

	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Sujet</th>
				<th>Contenu</th>
				<th>Nom</th>
				<th>Prénom</th>
				<th>Email</th>
			</tr>
		</thead>
		<tbody>
			{% for avi in avis %}
				<tr>
					<td>{{ avi.id }}</td>
					<td>{{ avi.sujet }}</td>
					<td>{{ avi.message }}</td>
					<td>{{ avi.nom }}</td>
					<td>{{ avi.prenom }}</td>
					<td>{{ avi.email }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	{{form(aviForm)}}{% endblock %}

templates/front/chambre_list.html.twig
{% extends "base.html.twig" %}

{% block body %}

	{% for chambre in chambres %}


		<div class="w33">
			<div class="w50">
				<h2>
					<a href="{{ path("front_chambre_show", {'id' : chambre.id}) }}">{{ chambre.titre }}</a>
				</h2>
				<p>{{ chambre.descriptionCourte }}</p>
			</div>
			<div class="w50">
				<img src="{{ asset('medias/' ~ chambre.photo) }}" alt="{{ chambre.titre }}">
			</div>
		</div>

	{% endfor %}
{% endblock %}

templates/front/chambre_show.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<img src="{{ asset("medias/" ~ chambre.photo) }}" alt="{{ chambre.titre }}" class="w100">

	<div class="w60">
		<h2>Equipements et informations</h2>
		<p>{{ chambre.descriptionLongue }}</p>
		<a href="{{ path('chambre_like', {'id' : chambre.id } ) }}" class="btn btn-link js-likes">

			{% if app.user and chambre.isLikeByUser(app.user) %}
				<i class="fas fa-thumbs-up"></i>
			{% else %}
				<i class="far fa-thumbs-up"></i>
			{% endif %}

			<span class="js-likes">{{ chambre.likes | length }}</span>
			<span class="js-label">J'aime</span>
		</a>

		<a href="{{ path('dislike_chambre', {'id' : chambre.id } ) }}" class="btn btn-link js-dislikes">

			{% if app.user and chambre.isDislikeByUser(app.user) %}
				<i class="fas fa-thumbs-down"></i>
			{% else %}
				<i class="far fa-thumbs-down"></i>
			{% endif %}
			<span class="js-dislikes">{{ chambre.dislikes | length }}</span>
			<span class="js-label">Je n'aime pas</span>

		</a>
	</div>


	<br><br>
	<hr class="w60">

	{{form_start(commandeForm)}}

	<div class="w50 mt-3">
		{{form_label(commandeForm.date_arrivee, "Date d'arrivée : ", {'label_attr' : {'class' : 'input-group-text', 'id' : 'basic-addon1'} } ) }}
		{{form_widget(commandeForm.date_arrivee,{'attr' : {'class ' : 'form-control'} } ) }}
	</div>

	<div class="w50 mt-3">
		{{form_label(commandeForm.date_depart, "Date de départ : ", {'label_attr' : {'class' : 'input-group-text', 'id' : 'basic-addon1'} } )}}
		{{form_widget(commandeForm.date_depart,{'attr' : {'class ' : 'form-control'} } )}}
	</div>
	<div class="w50 mt-3">
		{{form_label(commandeForm.prenom, "Prénom : ", {'label_attr' : {'class' : 'input-group-text', 'id' : 'basic-addon1'} } )}}
		{{form_widget(commandeForm.prenom,{'attr' : {'class ' : 'form-control'} } )}}

	</div>
	<div class="w50 mt-3">
		{{form_label(commandeForm.nom, "Nom : ", {'label_attr' : {'class' : 'input-group-text', 'id' : 'basic-addon1'} } )}}
		{{form_widget(commandeForm.nom,{'attr' : {'class ' : 'form-control'} } )}}
	</div>

	<div class="w50 mt-3">
		{{form_label(commandeForm.email, "Email : ", {'label_attr' : {'class' : 'input-group-text', 'id' : 'basic-addon1'} } )}}
		{{form_widget(commandeForm.email,{'attr' : {'class ' : 'form-control'} } )}}
	</div>

	<div class="w50 mt-3">
		{{form_label(commandeForm.telephone, "Téléphone : ", {'label_attr' : {'class' : 'input-group-text', 'id' : 'basic-addon1'} } )}}
		{{form_widget(commandeForm.telephone,{'attr' : {'class ' : 'form-control'} } )}}
	</div>

	<div class="w50 mt-3">
		{{form_widget(commandeForm.Reserver,{'attr' : {'class ' : 'btn btn-success'} } )}}
	</div>


	{{form_end(commandeForm)}}

	<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

	<script>


		function onClickLike(event) {
event.preventDefault();

const url = this.href;
const spanCount = this.querySelector("span.js-likes");
const icone = this.querySelector("i.fa-thumbs-up");

axios.get(url).then(function (response) {
spanCount.textContent = response.data.likes;
if (icone.classList.contains("fas")) {
icone.classList.replace("fas", "far");
} else {
icone.classList.replace("far", "fas");
}

if (response.data.message == "Le dislkie a été supprimé et le like a été ajouté") {
const spanCountDis = document.querySelector("span.js-dislikes");
const iconeDis = document.querySelector("i.fa-thumbs-down");

spanCountDis.textContent = response.data.dislikes;

if (iconeDis.classList.contains("fas")) {
iconeDis.classList.replace("fas", "far");
} else {
iconeDis.classList.replace("far", "fas");
}
}
}).catch(function (error) {
if (error.response.status === 403) {
window.alert("Vous devez obligatoirement vous connecter");
} else {
window.alert("Une erreur non identifiée s'est produite.");
}
});
}

function onCLickDislike(event) {
event.preventDefault();

const urlDislike = this.href;
const spanCountDislike = this.querySelector("span.js-dislikes");
const iconeDislike = this.querySelector("i.fa-thumbs-down");

axios.get(urlDislike).then(function (response) {
spanCountDislike.textContent = response.data.dislikes;

if (iconeDislike.classList.contains("fas")) {
iconeDislike.classList.replace("fas", "far");
} else {
iconeDislike.classList.replace("far", "fas");
}

if (response.data.message == "Le like a été supprimé et le dislike a été ajouté") {
const spanCountLike = document.querySelector("span.js-likes");
const iconeLike = document.querySelector("i.fa-thumbs-up");

spanCountLike.textContent = response.data.likes;

if (iconeLike.classList.contains("fas")) {
iconeLike.classList.replace("fas", "far");
} else {
iconeLike.classList.replace("far", "fas");
}
}
});
}

document.querySelector("a.js-likes").addEventListener("click", onClickLike);

document.querySelector("a.js-dislikes").addEventListener("click", onCLickDislike);
	</script>
{% endblock %}

templates/front/contact.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<form action="{{ path('email') }}" method="post">
		<div class="mb-3">
			<label for="exampleFormControlInput1" class="form-label">Email</label>
			<input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com" name="email">
		</div>
		<div class="mb-3">
			<label for="exampleFormControlInput2" class="form-label">Nom</label>
			<input type="text" class="form-control" id="exampleFormControlInput2" placeholder="nom" name="nom">
		</div>
		<div class="mb-3">
			<label for="exampleFormControlInput3" class="form-label">Prénom</label>
			<input type="text" class="form-control" id="exampleFormControlInput3" placeholder="prénom" name="prenom">
		</div>
		<div class="mb-3">
			<label for="exampleFormControlInput4" class="form-label">Sujet</label>
			<input type="text" class="form-control" id="exampleFormControlInput4" placeholder="sujet" name="sujet">
		</div>
		<div class="mb-3">
			<label for="exampleFormControlInput5" class="form-label">Catégorie</label>
			<select class="form-select" aria-label="Default select example" name="categorie" id="exampleFormControlInput5">
				<option selected>Choisisez la catégorie</option>
				<option value="Chambre">Chambre</option>
				<option value="Restaurant">Restaurant</option>
				<option value="SPA">Spa</option>
				<option value="Autre">Autre sujet</option>
			</select>
		</div>
		<div class="mb-3">
			<label for="exampleFormControlTextarea1" class="form-label">Message</label>
			<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="message"></textarea>
		</div>
		<div class="mb-3">
			<input type="submit" value="Envoyer" class="btn btn-success">
		</div>
	</form>

{% endblock %}

templates/front/email.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<h1>{{ sujet }}</h1>
	<h2>{{ categorie }}</h2>
	<h3>Message de
		{{ nom }}
		{{prenom}}</h3>
	<p>{{ message }}</p>

{% endblock %}

templates/front/home.html.twig
{% extends "base.html.Twig" %}

{% block body %}

	<main>

		<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
			<div class="carousel-indicators">
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
			</div>
			<div class="carousel-inner">
				<div class="carousel-item active">
					<img src="{{ asset('medias/' ~ sliders[0].photo) }}" class="d-block w-100" alt="photo">
				</div>
				{% for slider in sliders | slice(1,) %}
					<div class="carousel-item">
						<img src="{{ asset('medias/' ~ slider.photo) }}" class="d-block w-100" alt="...">
					</div>

				{% endfor %}

			</div>
			<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Previous</span>
			</button>
			<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Next</span>
			</button>
		</div>

		<div class="flex center">
			<a href="#" class="btn btn-primary margin">House Hotel | Découvrez nos chambres</a>
		</div>

		<div class="w50">
			<div class="w30">
				<img src="" alt="chambre">
				<h2>Chambre</h2>
				<span>Vener découvrir nos chambres</span>
				<a href="{{ path('front_chambre_list') }}" class="btn btn-secondary">Découvrir nos chambre</a>
			</div>
			<div class="w30">
				<img src="" alt="restaurant">
				<h2>Restaurant</h2>
				<span>Vener découvrir nos restaurant</span>
				<a href="#" class="btn btn-secondary">Découvrir nos restuarants</a>
			</div>
			<div class="w30">
				<img src="" alt="spa">
				<h2>SPA</h2>
				<span>Vener découvrir nos spa</span>
				<a href="#" class="btn btn-secondary">Découvrir nos spa</a>
			</div>
		</div>

	</main>


{% endblock %}

templates/front/search.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<h2>Les chambres qui correspondent à votre recherche : "{{ term }}" sont :</h2>

	{% for chambre in chambres %}
		<a href="{{ path('front_chambre_show', {'id' : chambre.id }) }}">
			<h3>{{ chambre.titre }}</h3>
		</a>
	{% endfor %}

{% endblock %}

templates/front/search_avis.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<h1>Avis selon le filtre :
		{{ term }}</h1>

	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Sujet</th>
				<th>Contenu</th>
				<th>Nom</th>
				<th>Prenom</th>
				<th>Email</th>
			</tr>
		</thead>
		<tbody>
			{% for avi in avis %}
				<tr>
					<td>{{ avi.id }}</td>
					<td>{{ avi.sujet }}</td>
					<td>{{ avi.message }}</td>
					<td>{{ avi.nom }}</td>
					<td>{{ avi.prenom }}</td>
					<td>{{ avi.email }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/front/user_form.html.twig
{% extends "base.html.twig" %}

{% block body %}

	{{form(userForm)}}{% endblock %}